### ISSUE TITLE
Items still drop

### ISSUE THREAD

**Issue by xakuvo** [SuperGamerTron/KeepInventory#1] opened 2021-07-13 00:30 UTC
Items still drop on death.
Experienced in several different multiplayer games, hosted by me, where all players were running the mod. 
Sometimes items would drop upon resurrection, after being retained in inventory for ~1 second.  Other times items would simply drop on death as normal.

**Comment by SuperGamerTron** [comment] 2021-07-13 03:37
Thanks for reporting this issue. Were you using any other mods during those games, and were there any times that it worked?

**Comment by Unhall0w3d** [comment] 2021-07-13 21:31
This issue is happening for me and my friends as well. This is using the latest version of Muck coupled with the following mod list, I have tried installing manually and using Thunderstore with the same issues as described by Xakuvo.

All mods are at the latest version available on the site as of 5:30PM 7/13/2021 and the issue is still present. 

BepInExPack_Muck
MuckUpgradeBuildings
SettingsApi
Chests_On_Map
BetterRunning (by delusional)
Rings_Galore_API
Better_Statistics
BetterStackLimits
PacketHelper
ShareEm
MuckApi
MuckServerBrowser
ObamiumStuff

**Comment by SuperGamerTron** [comment] 2021-07-13 21:34
Alright, I'll do some tests later with those mods when I have time since I'm a bit busy right now.

**Comment by SuperGamerTron** [comment] 2021-07-15 06:25
I've done some testing with those mods and I haven't been able to reproduce the issue. Can the host and another person enable logging in the BepInEx config if it isn't already, and send the `LogOutput.log` file in the BepInEx folder once the issue happens again?

**Comment by xakuvo** [comment] 2021-07-15 14:32
I will attempt to provide.
It may be a while to get some people together to test.
The mod did occasionally work. It may have begun to fail after multiple
hosted sessions within the same game instance.

**Comment by kristian-skistad** [comment] 2021-07-22 04:22
Having the same issue. Seems to occur more frequently with larger parties (3+) and longer sessions almost always cause the drop to happen. No other mods installed.

**Comment by SuperGamerTron** [comment] 2021-07-22 05:05
I think I have an idea of where it could be coming from, I'll update the mod with a fix.

**Comment by SuperGamerTron** [comment] 2021-07-22 06:39
New version has been uploaded to the [thunderstore](https://muck.thunderstore.io/package/SuperGamerTron/KeepInventory/), should be fixed now,

**Closed as completed** 2022-01-25 02:27 UTC
